[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "libGL",
  "libGLU", 
  "mesa",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "glib"
]

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:$PORT"